FROM node:16-alpine

# Hacer la carpeta 'app' el directorio de trabajo actual
WORKDIR /app

# Copiar 'package.json' y 'package-lock.json' (si están disponibles)
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar los archivos y carpetas del proyecto al directorio de trabajo actual
COPY . .

# Construir aplicación para producción minificada
RUN npm run build

# Instalar un simple servidor http para servir nuestro contenido estático
RUN npm install -g http-server

# Exponer el puerto que utilizará http-server
EXPOSE 8080

# Comando para ejecutar el servidor http
CMD ["http-server", "dist", "-p", "8080"]
